# Generated by Django 5.1.5 on 2025-01-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
